//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractPayment
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int PaymentNo { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public string cr_by { get; set; }
        public Nullable<System.DateTime> cr_at { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
